keys:
    - &bandithedoge age1d0elpvhcazscprkg27vqwgpg202jlx95t3y8waadn4wtfhw7tpgq6t2vwh

creation_rules:
    - path_regex: secrets.(yaml|json|env|ini)$
      key_groups:
          - pgp:
            age:
                - *bandithedoge
