[default.files]
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"topgrade.toml" = "~/AppData/Roaming/topgrade.toml"
"terminal.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json"
"powershell.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"