#! /bin/bash

# pywal colors
wal -R -n

# screens
~/.screenlayout/xrandr.sh

# startup shit
sxhkd &					              	# hotkey daemon
lxsession &				              	# for apps that need authorization
nitrogen --restore &	        			# set wallpaper from nitrogen
dunst &                                     # notification daemon
picom &                              		# compositor (transparency, shadows, etc.)
~/.config/polybar/launch.sh	      		# polybar

# monitors
for m in $(bspc query --monitors --names); do
    bspc monitor $m -d 1 2 3 4 5 6 7 8 9 10
done

# windows
bspc config border_width 2		        	# borders
bspc config window_gap 10			        # FUCKEN GAPS!!11111!!111!
bspc config focus_follows_pointer true		# hover to focus
bspc config gapless_monocle true            # no gaps in monocle layout
bspc config borderless_monocle true         # no borders in monocle layout

# colors
bspc config normal_border_color "#282828"
bspc config active_border_color "#665c54"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

# window rules
bspc rule -a feh state=floating focus=on
bspc rule -a Galculator state=floating focus=on
bspc rule -a Piper state=floating focus=on
bspc rule -a flameshot state=floating focus=on
bspc rule -a Lutris state=floating focus=on
bspc rule -a kruler state=floating focus=on
bspc rule -a Gcolor3 state=floating focus=on
bspc rule -a Sxiv state=floating focus=on
bspc rule -a nsusbloader.NSLMain state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a vlc state=floating focus=on
bspc rule -a Nfoview state=floating focus=on
bspc rule -a Cinelerra state=floating focus=on
bspc rule -a mpv state=floating focus=on
bspc rule -a Emacs state=tiled focus=on
